backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "[Demo] Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Products", name: products, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Values", name: "values", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/contact/_index.md"
        label: "[Demo] Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/products/_index.md"
        label: "[Demo] Products Page"
        name: "products"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "site/content/values/_index.md"
        label: "[Demo] Values Page"
        name: "values"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: Values
            name: values
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}

      # ---  artwork page ---
      - file: "site/content/artwork/_index.md"
        label: "Artwork Page"
        name: "artwork"
        fields:
          - {label: Title, name: title, widget: string}
          - label: Murals
            name: murals
            widget: list
            fields:
              - {label: ID, name: id, widget: string}
              - {label: Date, name: date, widget: string}
              - {label: Image, name: imageUrl, widget: image}
              - {label: "Lead Artist", name: leadArtist, widget: string}
              - {label: Location, name: location, widget: string}
              - {label: "Thumbnail Image", name: thumbUrl, widget: image}
              - {label: Title, name: title, widget: string}
              - {label: Color, name: boxColor, widget: select, options: ["red", "yellow", "blue"]}
          - label: FAQs (Artwork)
            name: faqs
            widget: list
            fields:
              - {label: Question, name: question, widget: string}
              - {label: Answer, name: answer, widget: markdown}

      # ---  about us page ---
      - file: "site/content/about_us/_index.md"
        label: "About Us Page"
        name: "about_us"
        fields:
          - name: pageHeader
            label: "Page Header (About Us)"
            widget: object
            fields:
            - {label: Title, name: title, widget: string}
            - {label: Caption, name: caption, widget: text}
            - {label: Image, name: imageUrl, widget: image}
            - {label: Color, name: boxColor, widget: select, options: ["red", "yellow", "blue"]}
          - {label: "Mission Statement", name: missionStatement, widget: text}
          - name: teamMembers
            label: "Our Team"
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Role, name: role, widget: string}
              - {label: Image, name: imageUrl, widget: image}
              - {label: Email, name: email, widget: string}
          - label: "Board of Directors"
            name: directors
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Role, name: role, widget: string}
              - {label: Image, name: imageUrl, widget: image}
              - {label: Email, name: email, widget: string}
          - label: "Advisory Committe"
            name: advisors
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Role, name: role, widget: string}
              - {label: Image, name: imageUrl, widget: image}
              - {label: Email, name: email, widget: string}
          - label: Press
            name: press
            widget: list
            fields:
              - {label: Headline, name: headline, widget: string}
              - {label: Date, name: date, widget: string}
              - {label: Color, name: boxColor, widget: select, options: ["red", "yellow", "blue"]}
              - {label: Image, name: imageUrl, widget: image}
              - {label: URL, name: linkUrl, widget: string}
              - {label: Publication, name: publication, widget: string}
              - {label: Text, name: text, widget: text}

      # ---  programs page ---
      - file: "site/content/programs/_index.md"
        label: "Programs Page"
        name: "programs"
        fields:
          - name: pageHeader
            label: "Page Header (Programs)"
            widget: object
            fields:
            - {label: Title, name: title, widget: string}
            - {label: Caption, name: caption, widget: text}
            - {label: Image, name: imageUrl, widget: image}
            - {label: Color, name: boxColor, widget: select, options: ["red", "yellow", "blue"]}
          - name: programs
            label: Programs
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Text, name: text, widget: markdown}
              - {label: Details, name: details, widget: string}
              - {label: Price, name: price, widget: string}
              - {label: Image, name: imageUrl, widget: image}
              - {label: Color, name: boxColor, widget: select, options: ["red", "yellow", "blue"]}
          - name: faqs
            label: FAQs (Programs)
            widget: list
            fields:
              - {label: Question, name: question, widget: string}
              - {label: Answer, name: answer, widget: markdown}
          - name: photos
            label: "Photos"
            widget: list
            fields:
              - {label: Image, name: imageUrl, widget: image}

      # ---  events page ---
      - file: "site/content/events/_index.md"
        label: "Events Page"
        name: "events"
        fields:
          - name: events
            label: Events
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: markdown}
              - {label: Date, name: date, widget: string}
              - {label: Image, name: imageUrl, widget: image}
              - {label: Color, name: boxColor, widget: select, options: ["red", "yellow", "blue"]}
          - name: photos
            label: "Photos"
            widget: list
            fields:
              - {label: Image, name: imageUrl, widget: image}

      # ---  services page ---
      - file: "site/content/services/_index.md"
        label: "Services Page"
        name: "services"
        fields:
          - name: pageHeader
            label: "Page Header (Services)"
            widget: object
            fields:
            - {label: Title, name: title, widget: string}
            - {label: Caption, name: caption, widget: text}
            - {label: Image, name: imageUrl, widget: image}
            - {label: Color, name: boxColor, widget: select, options: ["red", "yellow", "blue"]}
          - name: cards
            label: Info Cards
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Image, name: imageUrl, widget: image}
              - {label: Description, name: description, widget: markdown}
              - {label: "Action URL", name: linkUrl, widget: string}
              - {label: "Action Text", name: linktext, widget: string}
              - {label: Color, name: boxColor, widget: select, options: ["red", "yellow", "blue"]}

      # ---  get involved page ---
      - file: "site/content/get_involved/_index.md"
        label: "Get Involved Page"
        name: "get_involved"
        fields:
          - name: pageHeader
            label: "Page Header (Get Involved)"
            widget: object
            fields:
            - {label: Title, name: title, widget: string}
            - {label: Caption, name: caption, widget: text}
            - {label: Image, name: imageUrl, widget: image}
            - {label: Color, name: boxColor, widget: select, options: ["red", "yellow", "blue"]}
          - name: cards
            label: Info Cards
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Image, name: imageUrl, widget: image}
              - {label: Description, name: description, widget: markdown}
              - {label: "Action URL", name: linkUrl, widget: string}
              - {label: "Action Text", name: linktext, widget: string}
              - {label: Color, name: boxColor, widget: select, options: ["red", "yellow", "blue"]}
          - label: FAQs (Get Involved)
            name: faqs
            widget: list
            fields:
              - {label: Question, name: question, widget: string}
              - {label: Answer, name: answer, widget: markdown}
